_meta:
  ae_version: 1.0.0
  created_at: '2026-07-22T19:47:07.711563+08:00'
  schema_version: 1
ci_platform: github
current_day: '22'
current_month: '07'
current_year: '2026'
language: typescript
os: macos
package_manager: pnpm
project_description: ''
project_name: Design-Solution-AiPilot
project_type: 中小型办公（5–15
repo_description: ''
repo_name: Design-Solution-AiPilot
sep: /
test_runner: ''
use_docker: false
use_lefthook: false
